apiVersion: 1

prune: true

datasources:
  - name: FieldWorks InfluxDB
    uid: fieldworks-influxdb
    type: influxdb
    access: proxy
    url: "${INFLUX_URL}"
    isDefault: true
    editable: false
    jsonData:
      version: Flux
      organization: "${INFLUX_ORG}"
      defaultBucket: "${INFLUX_BUCKET}"
      timeInterval: 1m
    secureJsonData:
      token: "${INFLUX_TOKEN}"
